### ISSUE TITLE
Bad request?

### ISSUE THREAD

**Issue by Ratismal** [DasWolke/better-cleverbot-client#1]
When I try to query, I get this error
```
Error: Request failed with status code 400
    at createError (C:\Users\cat\drive\JS\blargbot\node_modules\axios\lib\core\createError.js:15:15)
    at settle (C:\Users\cat\drive\JS\blargbot\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\cat\drive\JS\blargbot\node_modules\axios\lib\adapters\http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This seems to happen with the official driver too. Any ideas?

**Comment by DasWolke** [comment]
Blame their api :<
